- cli/config.go
Allows to configure active tctl version 
For smooth upgrade from tctl v1 to v2.
Allows to keep users on v1 while giving option to switch to v2.
Later v2 will be set as the default
1. Closes 
Locally `./tctl config set version 2` and checking the resulting config file
Requires README mentioning this and other configuration options
> Allow configuring tctl version

- cli_curr/main.go
- cmd/main.go
- go.mod
- go.sum
Integrates tctl from Temporal Server
Sets it as default
As part of the release process of the new tctl, keep users on the old one for a while until the new tctl is officially ready
1. Closes 
tests + 
plus locally `make` and ensure old tctl workflow and admin workflow commands work 
Not for this PR. Generally yes - info on switching to tctl next
> Integrate server tctl and make it default 

- cli/flags.go
- cli/workflowCommands.go
- go.mod
Cherry pick of https://github.com/temporalio/temporal/pull/1859.
> Switch memo and search attribute flags to StringSlice

- Makefile
- cli/app_test.go
Adds unit testing scripts to Makefile
Adds refactored unit tests from https://github.com/temporalio/temporal 
QA
1. Closes 
Ran the tests
> Create unit testing

- cli/activity.go
- cli/activityCommands.go
- cli/app.go
- cli/app_test.go
- cli/batch.go
- cli/batch_commands.go
- cli/cluster_commands.go
- cli/config.go
- cli/data_converter_commands.go
- cli/defs.go
- cli/flags.go
- cli/namespace.go
- cli/namespaceCommands.go
- cli/namespaceUtils.go
- cli/taskQueue.go
- cli/taskQueueCommands.go
- cli/util.go
- cli/workflow.go
- cli/workflowCommands.go
- Refactored error handling to always return errors to urfave/cli/v2
- Updated some of the error messages
- Removed `getRequiredOption`, updated command flags adding Required flag accordingly 
- streamlines and centralizes error handling, fits unit tests expectation
- getRequiredOption was adding arbitrary limitations that were not enforced by the temporal API, which is highly questionable approach. This was only making `tctl` harder to use because of seeing more error messages for arbitrary limitations, when in fact the API would allow such values
1. Closes 
unit tests (tbu)
> Refactor error handling

- .github/workflows/test.yml
Adds CI pipeline for PRs unit testing
**note** failure is expected since the tests are not fully adapted to the new commands design and error handling
CI
1. Closes 
- github action is to be tested by the PR 
> Create github actions CI pipeline

- Makefile
- cli/app.go
- cli/app_test.go
- fixed error handling in unit tests (in accordance with the urfave/cli/v2 error handling and our refactoring)
- updated flag names in unit tests to their full names
- fixing CI
- flag names should be passed as full names for simpler maintainability
1. Closes 
Ran the tests (including the other open PRs)
> Fix unit tests and align with error handling

- cli/namespaceCommands.go
fixes issue where `namespace describe` could exit with error code 1 (caught by unit tests)
`namespace describe` shouldn't be failing on such nil data
1. Closes 
unit tests
> Fix namespace print

- cli/workflowCommands.go
Updates error messages for workflow commands
resolving linting issues, unifying the syntax etc
1. Closes 
> Update workflow commands error messages

- cli/flags.go
- cli/namespaceUtils.go
- cli/workflow.go
Fixed the flags for `workflow observe` and `namespace register` 
- `workflow observe` didn't have pagination, formatting and other flags from the new tctl
- `namespace register` doesn't require `--namespace-data`
1. Closes 
unit tests
> Fix flags for workflow observe & namespace register

- cli/activity.go
- cli/activityCommands.go
- cli/app.go
- cli/batch.go
- cli/cluster.go
- cli/flags.go
- cli/namespaceUtils.go
- cli/taskQueue.go
- cli/workflow.go
- pkg/flags/flags.go
Adapted flags aliases to urfave/cli v2 interface
urfave/cli v2 flags interface has changed in v2. Fixed the aliases to work 
1. Closes 
unit tested that there is no collision of aliases
> Adapt flags aliases to urfave/cli v2

- .github/workflows/goreleaser.yml
Added pre-releases to trigger goreleaser pipeline
Would like the binaries for pre-releases too https://github.com/temporalio/tctl/releases/tag/v1.14.0-alpha
1. Closes 
Not tested
> Include pre-releases in goreleaser

- go.mod
upgrades to golang v1.17
1. Closes 
`make test`
> Upgrade to golang v1.17

- cli/factory.go
- cli/factory_test.go
- cli/util.go
For details see https://github.com/temporalio/temporal/pull/2062 :
"This PR replaces the existing io/ioutil functions with their new definitions in io and os packages."
For details see https://github.com/temporalio/temporal/pull/2062
1. Closes 
`make test`
> Deprecate io/ioutil

- .devcontainer/Dockerfile
- .devcontainer/Dockerfile.temporalite
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .devcontainer/library-scripts/common-debian.sh
- .devcontainer/library-scripts/docker-debian.sh
- .devcontainer/library-scripts/go-debian.sh
- .editorconfig
- .vscode/launch.json
Adding devcontainer to support working in GitHub Codespaces and vscode remote-container extension
for demos and other goodness
1. Closes 
In GitHub Codespaces!
Locally using VSCode remote-container extension
> Adding devcontainer for code-spaces

- cli/activityCommands.go
- cli/app.go
- cli/cluster.go
- cli/cluster_commands.go
- cli/config.go
- cli/defs.go
- cli/namespaceCommands.go
- cli/taskQueue.go
- cli/taskQueueCommands.go
- cli/workflow.go
- cli/workflowCommands.go
- cli_curr/defs.go
- config/config.go
- go.mod
- go.sum
updates module name
https://github.com/temporalio/tctl-kit/pull/5
1. Closes 
unit tests
> Update naming of tctl-kit module

- cli/app.go
- cli/plugin.go
- cli/use_dynamic_commands.go
- go.mod
- go.sum
Adds plugins support for tctl
Plugins are expected to be binary executables and searchable in $PATH
`tctl my-plugin visualize-workflows`
Allows users extend tctl functionality
1. Closes 
Executed a binary located under $PATH (no tests yet)
> Add support for external plugins

- .github/workflows/trigger-publish.yml
- Triggers update of tctl submodule in https://github.com/temporalio/docker-builds
- Results in docker images builds & publish for auto-setup, server and admin-tools images
and moving to Github Actions
1. Closes 
> Add pipeline to trigger Temporal docker images build

- cli/config.go
Allows to configure multiple params at a time:
```
$ tctl config set --namespace accounting --address 127.0.0.1:7233
namespace: accounting
address: 127.0.0.1:7233
$ tctl config get --namespace --address
namespace: accounting
address: 127.0.0.1:7233
$ cat ~/.config/temporalio/tctl.yaml
active: local
aliases: {}
environments:
local:
address: 127.0.0.1:7233
namespace: accounting
version: next
```
per comments in proposal https://github.com/temporalio/proposals/pull/39
1. Closes 
> Allow configuring multiple flags at a time

- cli/headersprovider/headers_provider.go
- cli_curr/app.go
- cli_curr/factory.go
- cli_curr/headersprovider/headers_provider.go
- cli_curr/util.go
- cli_curr/workflowCommands.go
Imports were corrected to reference the local code for utility functions.
Prior to this change the local version of the code for these utilities was not used.
> Import local copies of utilities.

- .vscode/launch.json
updating launch.json paths to tctl
tctl main.go was moved
1. Closes 
> Correct vscode launch.json paths

- cli/util.go
Fixed reading flag values from config
1. Closes 
switched between setting a --flag, setting through config and using default values
> Fix reading values from config

- cli/activity.go
- cli/app_test.go
- cli/commands.go
- cli/config.go
- cli/data_converter.go
- cli/flags.go
- cli/taskQueue.go
- cli/workflow.go
- cli/workflowCommands.go
Updated some of the texts in --help output to be more consistent/concise
improving UX
1. Closes 
> Make --help output more consistent

- cli/namespaceCommands.go
- cli_curr/namespaceCommands.go
> Print isGlobal field for namespace record

- cli/app_test.go
- cli/flags.go
- cli/workflowCommands.go
- Switched to List Workflows API instead of `ListOpenWorkflows` and `ListClosedWorkflows`
- List Worklfows returns both Open and Closed workflows instead of requiring users to pass `--open` flag
1. Closes 
`tctl w l` and unit tests
> Switch to ListWorkflows API for fetching workflows

- cli/app_test.go
- cli/flags.go
- cli/workflow.go
- cli/workflowCommands.go
- added a flag `--archived` to `tctl worfklow list`
- removed separate command `tctl workflow listarchived`
- merging commands after after discussions here https://github.com/temporalio/tctl/pull/162 and on slack
1. Closes 
updated unit tests & executing manually
> Merge list archived workflows into workflow list command

- cli/workflow.go
Updated some of the --help messages based on https://docs.temporal.io/docs/tctl/workflow
fixing --help output spelling, such as `--reset-reapply-type value    ... Support one of these: ,Signal,NoneDefault to: All`
1. Closes 
> Update --help output for workflow commands

- cli/flags.go
- cli/namespace.go
- cli/namespace_utils.go
- cli/workflow.go
- Capitalized terms such as Workflow Execution, Namespace
- reordered commands under `tctl namespace`
- Fixed some spacing in --help
consistency in Help output and semantics
1. Closes 
> Capitalize terms in --help output

- cli/flags.go
- cli/workflow.go
Fixes printing raw details of worklfow execution with a `--raw` flag
These details include Search Attributes 
`tctl workflow describe` by default decodes search attributes and does some additional processing
1. Closes 
> Fix printing raw workflow execution details

- cli/flags.go
Update global namespace alias
Update global namespace alias from gd to gn in cli v2.
This alias will be different between v1 and v2. Not sure if this is an issue.
1. Closes 
> Update global alias

- cli/flags.go
Update namespace data alias from dmd to nd
Update namespace data alias to match the naming
1. Closes 
> Update namespace data alias

- cli/app.go
- cli/app_test.go
- cli/cluster_commands.go
- cli/factory.go
- cli/namespace.go
- cli/namespace_commands.go
- cli/namespace_utils.go
- cli/util.go
Add `namespace delete` command.
To support new `DeleteNamespace` API.
> Add namespace delete command

- cli/flags.go
- cli/workflow.go
- cli/workflow_commands.go
Add `workflow delete` command.
To expose `DeleteWorkflowExecution` API through `tctl`.
> Add workflow delete command

- cli_curr/namespaceCommands.go
Check nil pointers
It currently would crash on nil pointer if certain fields in resp are not set
1. Closes 
Local testing
> Make printNamespace() safe to nil pointer in resp

- cli_curr/app.go
- cli_curr/workflow.go
(most other descriptions don't have periods)
> Remove "new" and periods

- cli/app.go
- go.mod
- go.sum
Revers urfave/cli to v2.4.0
urfave/cli introduced a change that would use a comma in StringSlice inputs as a delimiter for separate values https://github.com/urfave/cli/pull/1241 . This breaks passing inputs where comma is a proper portion of the value and not a delimiter
1. Closes 
> Revert urfave cli to fix passing --input with comma

- .gitignore
> Gitignore vscode logs

- cli/util.go
- cli_curr/util.go
Adjusted code which normalises the response from a prompt to correctly remove all whitespace on Windows.
Without this the code would never consider that the response was "y" so would never take the action being confirmed.
1. Closes #243 
I'm not able to test this without access to a Windows machine but I don't believe it's a risky change.
No.
> Correctly process prompt response on Windows.

- README.md
- cli/app.go
- cli/data_converter_commands.go
- cli/factory.go
- cli/headersprovider/headers_provider.go
- cli/util.go
- cli/util_test.go
- cli/workflow_commands.go
- cli_curr/app.go
- cli_curr/factory.go
- cli_curr/util.go
- cli_curr/workflowCommands.go
- cmd/plugins/tctl-authorization-plugin/main.go
- cmd/tctl/main.go
- go.mod
sets the new tctl version as v2
aligning with semver as some of the changes are breaking -> upgrade of the major version  
1. Closes 
> Set new tctl version as v2

- cli/workflow.go
Updated the --help texts of `tctl workflow` commands
attempt to make it nicer to read
1. Closes 
> Update workflow --help texts

- Makefile
- cli/namespace_commands.go
replaced script that was manually finding test dirs with a built-in syntax
- simplify maintenance by using build-ins
- remove un-needed code (timeout etc is controlled by CI scripts)
1. Closes 
- ran `make` 
- GHA pipelines
> Update makefile test syntax

- cli/alias.go
- cli/commands.go
- cli/config.go
- cli/config_test.go
- cli/env.go
- cli/env_test.go
- cli/use_dynamic_commands.go
- cli_curr/config.go
- go.mod
- go.sum
Refactored config feature to adapt to the new config API https://github.com/temporalio/tctl-kit/pull/23
the new API is way more stable 
1. Closes 
updated unit tests
> Update to new config API

- cli/cluster_commands.go
- cli/env.go
- cli/namespace_commands.go
- cli/schedule_commands.go
- cli/workflow_commands.go
- go.mod
- go.sum
Implements API changes from https://github.com/temporalio/tctl-kit/pull/24
Making the commands print data more predictable
1. Closes 
unit tests + manually executing workflow list etc
> Explicitly set pagers and adapt to the new API

- cli/app_test.go
- cli/commands.go
- cli/search_attribute.go
- cli/search_attribute_commands.go
- cli/search_attribute_test.go
Moved `search-attribute` to a top level command instead of being under cluster
easier discoverability
discussed on an API review with @bergundy @alexshtin @yiminc
1. Closes 
existing unit test
> Make search attribute a top level command

- cli/activity.go
- cli/app.go
- cli/batch.go
- cli/flags.go
- cli/namespace_utils.go
- cli/schedule.go
- cli/schedule_commands.go
- cli/task_queue.go
- cli/workflow.go
removed alias for --context-timeout 
shouldn't be used much, cleaner --help output
1. Closes 
> Remove longer or less used aliases

- cli/batch.go
- cli/batch_commands.go
- cli/batch_test.go
- cli/flags.go
- go.mod
- go.sum
- `tctl batch list` now uses official API
- reworked it to use `tctl-kit` API for consistency in formatting. It also now prints Table by default
- added unit test
before
```
tctl batch list
[
{
"closeTime": "2022-09-21T00:41:42Z",
"jobId": "7b1533e9-adcc-4d79-b081-d4604dcb95f3",
"operator": "player0",
"reason": "sus",
"startTime": "2022-09-21T00:41:39Z",
"status": "Completed"
}
]
```
After
```
tctl batch list 
State                   JobId                    StartTime     
Completed  7b1533e9-adcc-4d79-b081-d4604dcb95f3  23 minutes ago
```
--help: 
```
tctl batch list -h
NAME:
tctl batch list - List batch operation jobs
USAGE:
tctl batch list [command options]  
OPTIONS:
--fields value            customize fields to print. Set to 'long' to automatically print more of main fields
--limit …
```
> Refactor batch list to use API

- cli/search_attribute.go
- cli/search_attribute_commands.go
- cli/search_attribute_test.go
Use `ListSearchAttributes` instead of GetSearchAttributes.
Future deprecation of `GetSearchAttributes` API.
> Use ListSearchAttributes instead of GetSearchAttributes

- cli/app.go
- cli/task_queue.go
- cli/task_queue_commands.go
Added to `task-queue describe` usage output.
Is there a better way to wrap text?
Explain how poller list works to avoid users thinking there are ghost workers.
> Clarify task-queue describe

- cli/batch.go
- cli/batch_commands.go
- cli/batch_test.go
- cli/flags.go
- cli/workflow.go
- cli/workflow_commands.go
- go.mod
- `tctl batch start` now uses official API
- added unit test
stabilizing by using the official API
1. Closes 
manual + added unit test
> Refactor batch start to use API

- cli/batch_commands.go
- cli/env.go
- cli/namespace_commands.go
- cli/schedule_commands.go
- cli/search_attribute_commands.go
- cli/task_queue_commands.go
- cli/workflow_commands.go
- go.mod
- go.sum
Printing of Tables/JSON now returns errors and is handled through urfave/cli error handler.
Standardizes error handling.
> Return errors when printing tables/etc

- cli/cluster.go
- cli/cluster_commands.go
- cli/cluster_test.go
- cli/env.go
- cli/flags.go
- cli/search_attribute.go
- cli/search_attribute_commands.go
- cli/task_queue.go
- go.mod
- go.sum
Added `tctl cluster system` that prints System info
```
tctl cluster system --fields long
ServerVersion  SupportsSchedules  UpsertMemo  SignalAndQueryHeader  ActivityFailureIncludeHeartbeat  InternalErrorDifferentiation  
1.18.0         true               true        true                  true                             true
```
Helps users figure out server version and what is supported
1. Closes 
Tested against a local deployment. I would like to add a test though because this API is not supported by SDK yet it's a bit more complicated to mock it (similar test is wip in a different PR https://github.com/temporalio/tctl/pull/280, might add it here once i figure out how to do that) 
> Add system info command

- cli/activity.go
- cli/activity_commands.go
- cli/batch_commands.go
- cli/schedule_commands.go
- cli/search_attribute_commands.go
- cli/task_queue_commands.go
- cli/util.go
- cli/workflow_commands.go
- cmd/tctl/main.go
Stopped swallowing the error message about missing required flags
helps understand what is missing
1. Closes 
```
tctl workflow describe
2022/09/27 19:23:06 Required flag "workflow-id" not set
```
> Print error when required flag is not set

- cli/cluster.go
- cli/cluster_commands.go
- cli/cluster_test.go
added command to describe cluster
visibility into cluster
1. Closes 
added unit test + manual run
> Add cluster describe

- cli/flags.go
- cli/schedule.go
- cli/workflow.go
- cli/workflow_commands.go
- Removed repeated sentences in `tctl workflow reset`
- renamed --type into --workflow type for `tctl schedule create`
typing experience
1. Closes 
> Remove repeated sentences in reset

- cli/defs.go
- cli/flags.go
- cli/namespace_commands.go
- cli/namespace_utils.go
- cli/workflow.go
- cli/workflow_commands.go
Removed bad binary from `workflow reset` and `namespace update`
This functionality is not well tested and needs a bigger overview of how it should work in Temporal and tctl
1. Closes 
tests + manually run namespace update
> Remove bad binary functionality

- cli/cluster.go
- cli/cluster_commands.go
- cli/cluster_test.go
- cli/flags.go
Added 
* `tctl cluster upsert`
* `tctl cluster list`
* `tctl cluster delete`
allows to manage remote clusters
1. Closes 
manual execution (`tctl cluster list`) + unit tests
> Add commands to upsert list and remove remote cluster

- cli/app.go
- cli/headers/headers.go
Bumps versions of tctl to `v1.16.3` and `v2.0.0-beta.2`
new patch release
1. Closes 
> Bump version to v1.16.3

- cli/namespace_commands.go
- cli_curr/namespaceCommands.go
> Print failover related info in ns record

- README.md
Update Readme for set version to current
Update Readme for set version to current
1. Closes 
> Update Readme for set version to current

- cli/app.go
- cli/headers/headers.go
Minor version bump
new release with Schedules
1. Closes 
> Bump version to v1.17.0

- cli/schedule_commands.go
- cli_curr/schedule_commands.go
Fix potential npe when listing schedules without ES
1. Closes 
> Fix nil pointer in uncanonicalizeSpec

- cli_curr/app.go
- cli_curr/batchv2.go
- cli_curr/batchv2_commands.go
- cli_curr/workflow.go
- cli_curr/workflowCommands.go
Adds API based batch commands to v1
`tctl workflow cancel --query ...`
`tctl workflow signal --query ...`
`tctl workflow terminate --query ...`
commands for the new APIs 
1. Closes 
> Add batch-API commands to tctl v1

- cli/app.go
- cli/headers/headers.go
- Set version to v1.17.1
- updated the version of the next cli to "next"
- new release v1.17.1
- removing the notion of v2 since tctl itself will remain as v1 version & syntax
1. Closes 
> Bump version to v1.17.1

- cli/headers/headers.go
Updated version
new release
1. Closes 
tests
> Bump version to v1.17.2

- .vscode/launch.json
- cli/app.go
Added a `tctl next` deprecation warning
tctl next has been moved to https://github.com/temporalio/cli
1. Closes 
> Add tctl next deprecation message

- cli_curr/batchv2_commands.go
Checking error returned from API before accessing the returned value in
ListBatchJobsV2.
Currently, running `tctl batch-v2 list` produces the following due to nil
pointer dereference. This is caused by not checking the error before reading the
returned value. 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10121c1a0]
goroutine 1 [running]:
github.com/temporalio/tctl/cli_curr.ListBatchJobsV2.func1({0x0, 0x0, 0x0})
github.com/temporalio/tctl/cli_curr/batchv2_commands.go:78 +0x100
go.temporal.io/server/common/collection.(*PagingIteratorImpl[...]).getNextPage(0x1018ad140)
go.temporal.io/server@v1.18.1-0.20230217005328-b313b7f58641/common/collection/pagingIterator.go:116 +0x38 …
```
> Check error from API before using response

- .github/workflows/goreleaser.yml
- .github/workflows/test.yml
- go.mod
Bump Go version to 1.20
1. Closes 
> Bump Go version to 1.20
