pkg/output/printer.go
Changed --no-pager to print all of the pages instead of just one
makes --no-pager responsible for a single thing - printing into stdout. It shouldn't change the behavior of how many pages are printed
1. Closes 
ran locally on large # of items, verified all of the items are printed
`./tctl workflow list --no-pager`
no
=> Make --no-pager print all pages, not just one

cli_curr/config.go, cli_curr/main.go, cmd/main.go
**What changed?**
Adds config feature to tctl
```bash
./tctl config set version next
```
**Why?**
Will allow to switch to experimental `next` version of tctl UX by running
**How did you test it?**
```bash
./tctl config set version next
```
and checking config file
**Potential risks**
no risks
**Is hotfix candidate?**
no
=> Add config feature to old tctl

pkg/flags/flags.go, pkg/output/flag.go, pkg/output/printer.go, pkg/pager/flag.go
```bash 
./tctl w l --limit 5
WorkflowId                    RunId                   StartTime    
bee6469d___5  1a24aad1-da95-4ad2-899c-708fd538fb47  11 hours ago  
bee6469d___4  bb980f5d-1359-4e39-9802-eb61914b38ee  11 hours ago  
bee6469d___3  07688132-7d67-4171-937e-e0e4c51f1360  11 hours ago  
bee6469d___2  26bbadc8-a010-4465-b489-3617d5409541  11 hours ago  
bee6469d___1  493ddd84-bc4d-4d63-8c65-167e9a8fd2ea  11 hours ago
```
Adds a flag `--limit` to limit the number of items to print
Removes the flag `--pagesize`
Gives option to print limited number of items
1. Closes 
locally 
`./tctl w l --limit 10`
expected: prints 10 items
`./tctl w l --limit 0`
expected: prints 0 items (disables output, useful for commands such as `workflow run` )
3. Any docs updates …
=> Support limiting number of items to print 

pkg/flags/flags.go, pkg/output/flag.go, pkg/output/printer.go
Renamed flag `--columns` to `--fields`
As per recent comment and proposal update https://github.com/temporalio/proposals/pull/31#pullrequestreview-730152034
1. Closes 
```bash
./tctl config set version next
./tctl w l --fields "Execution.WorkflowId","Execution.RunId"
WorkflowId                       RunId                  
19547e_TimedOut        f08dd420-a736-4d1f-a424-9fd89034a2cd  
19547e_ContinuedAsNew  a504de26-b0b7-45f8-b5bf-f15c6abafab1  
9d1d5b_Running         37df046c-9cfb-406f-829f-33a3e90cd857  
19547e_Failed          db332742-8439-42b9-b9ec-e9dda775b87b  
19547e_ContinuedAsNew  497bb468-b7d8-43ee-967d-e793a3c35d80
```
yes
=> Rename --columns to --fields

pkg/flags/flags.go, pkg/format/time.go
Renamed flag `--format-time` to `--time-format`
As per recent comment and proposal update https://github.com/temporalio/proposals/pull/35#pullrequestreview-730151615
1. Closes 
```bash
./tctl config set version next
./tctl w l --time-format iso
WorkflowId                       RunId                       StartTime        
19547e_TimedOut        f08dd420-a736-4d1f-a424-9fd89034a2cd  2021-08-15T22:18:25Z  
19547e_ContinuedAsNew  a504de26-b0b7-45f8-b5bf-f15c6abafab1  2021-08-15T22:18:25Z  
9d1d5b_Running         37df046c-9cfb-406f-829f-33a3e90cd857  2021-08-11T22:42:20Z
```
yes
=> Rename --format-time to --time-format

cli/namespaceCommands.go, cli/workflowCommands.go
- reused workflow history printer for `workflow show` command
- updating in accordance to changes in `temporal` repo
- reusing code between `workflow observe`, `show` and `run` commands
1. Closes 
ran the commands. Unit tests tbu
=> Reuse workflow history helper between commands

cli/app_test.go
Renamed the flag name `--global_namespace` -> `--global-namespace`
Fixes the name
1. Closes 
- validated that unit tests don't complain about the flag name 
- additionally verified that there are no more flags with underscores in the tests using a regex
=> Fix --global-namespace flag name in tests

README.md, cli/activity.go, cli/app_test.go, cli/cluster.go, cli/commands.go, cli/namespace.go, cli/taskQueue.go, cli/workflow.go
* Removed aliases of the commands that perform write operations
* if users really want aliases for such opeartions, they can still do this by explicly configuring aliases using `alias` command  
* shortened the aliases of some commands
* would prefer users to explicitly type the names of commands that perform write operation. Users can still manually set up aliases for such commands
1. Closes 
unit tests
=> Rework commands aliases

pkg/iterator/iterator.go, pkg/output/json.go, pkg/output/printer.go
Removed `go.temporal.io` dependency from tctl's `pkg` module 
I want to use the CLI level tools to improve UX of tctl admins commands. These commands are implemented in temporal repo and are dependent on internal packages.
These CLI framework tools are implemented as `/pkg` module and provides
- CLI paginations 
- output formatting (table/json/card)
-  time formatting (relative/iso..) 
- coloring
- generic config feature 
- printing progress bar/time for long processes
- etc..
In order to be able to use these CLI framework tools in admin command, this requires to separate the tctl into two repos:
- cli framework tools (aka currently `/pkg` module in code`) - see details below
- tctl commands and implementation
The current PRs removes temporal dependencies from `/pkg`, so that i can …
=> Remove temporal dependencies from CLI framework level pkgs

cli/data_converter_commands.go
This allows the data converter to accept connections which have been port-forwarded, i.e., if the dataconverter is running in a VM and the browser is running natively.
Same commit in temporalio/temporal: https://github.com/temporalio/temporal/pull/2089
=> Changed tctl dataconverter to listen on 0.0.0.0 instead of 127.0.0.1

cli/flags.go, cli/namespaceCommands.go, cli/namespaceUtils.go, cli_curr/flags.go, cli_curr/namespaceCommands.go, cli_curr/namespaceUtils.go
Namespace state update needs more steps and should be handled by a workflow.
Update the state metadata should be just one step of the workflow.
We should create other command for tctl to trigger operations like DeleteNamespace.
=> Remove --state flag from namespace update command

cli/data_converter.go
Same commit in `temporal`: https://github.com/temporalio/temporal/pull/2093
=> Added ability to specify dataconverter port via flag

cli/activityCommands.go, cli/util.go, cli/workflowCommands.go, cli_curr/data_converter_commands.go, cli_curr/util.go, cli_curr/workflowCommands.go
**What changed?**
tctl will now use the custom data converter for printing query results.
**Why?**
This lines up with the SDK behaviour on the worker side which uses the custom data converter to encode the query response.
**How did you test it?**
Tested `tctl workflow stack` on a Temporal application using an encrypting data converter. Without this fix I see "[encoding binary/encrypted: payload encoding is not supported]". With this fix I see the query response as I'd expect.
**Potential risks**
None.
**Is hotfix candidate?**
No.
=> Use the custom data converter for query responses.

cli/data_converter_commands.go
Original PR in temporal server: https://github.com/temporalio/temporal/pull/2299
Moved here.
Original PR notes:
> Describe what has changed in this PR 
Removes any trailing slash that the user inputs to the dc cli command
> Tell your future self why have you made these changes 
It prevents this `https://<someURL>//data-converter/52352` and saves engineers the hours trying to figure out what went wrong.
> How have you verified this change? Tested locally? Added a unit test? Checked in staging env?
I built the tctl plugin and copied it to my path. I then verified that the URL was stripped of the slash. 
> Assuming the worst case, what can be broken when deploying this change to production?
tctl dc could be broken
> Is this PR a hotfix candidate or require that a notification be sent to the …
=> Remove trailing slash in dc tool user input

.github/workflows/docker.yml
Changes per-commit docker images to be tagged by shortened SHA instead of full
Before:
`docker pull temporalio/tctl:sha-aa17a4aba898a43d2bd74c94088b69348bc275d1`
After:
`docker pull temporalio/tctl:sha-5502441`
looks cleaner
1. Closes 
=> Shorten docker image SHA tags

cli/commands.go, cli/config.go
Adds dedicated `alias` command to add aliases for custom commands
simplifies usage and provides better help message than generic `tctl config set aliases.mycommand "workflwos list"`
1. Closes 
```
$ tctl alias --command wcard --alias "workflow list --output card"
aliases: workflow list --output card
$ tctl alias --command wjson --alias "workflow list --output json"
aliases: workflow list --output json
$ cat ~/.config/temporalio/tctl.yaml 
active: local
aliases:
wcard: workflow list --output card
wjson: workflow list --output json
environments:
local:
address: 127.0.0.1:7233
namespace: default
version: next
```
=> Create dedicated command to create aliases

.github/workflows/trigger-publish.yml
As per changes in https://github.com/temporalio/docker-builds/pull/23
Adds info regarding the submodule(or the current repo) and the branch name
Automating release process & patch releases
1. Closes 
Tested the code with personal repos and simulating the changes:
https://github.com/feedmeapples/gha-parent
https://github.com/feedmeapples/gha-child
=> Add repo and branch info when triggering Docker builds

cli/workflowCommands.go
Always apply the value of the max fields flag, regardless if it was specifically set or defaulted.
Prior to this change the default was ignored as we specifically checked if the
flag was set before applying its value (default or otherwise). This resulted
in the default behaviour actually using 0 via the default int value.
=> Apply default for max field length.

cli/app.go
Headers provider plugin is now initialised based on the flag.
The flag was present but ignored.
=> Add headers provider init code.

cli/commands.go
The "Operate XXX" language reads a bit oddly, so I have some suggestions here to make the main help screen a bit more natural sounding
* Removed `Temporal` from a few lines where that context is pretty obvious
* Made capitalization consistent
=> Some minor language cleanup on main help

Dockerfile
=> Bump dockerfile go version.

cli/config.go, cli/factory.go
Adds support for TLS vars in config 
Simplifies switching between different environments 
1. Closes 
tested switching between local and cloud envs 
=> Support TLS props in config feature

cli/app_test.go, cli/flags.go, cli/workflow.go, cli/workflowCommands.go
- Removed `workflow observe` command
- added it under `workflow show`  as a `--follow` flag
~ same command 
1. Closes 
=> Move workflow observe under show command as a flag

cli/workflowCommands.go
Removes additional output when printing Workflow History as JSON
resolve https://github.com/temporalio/tctl/issues/183
1. Closes 
passed the output into `jq` for verification
=> Fix workflow show command output incorrect JSON

cli/workflowCommands.go, cli_curr/workflowCommands.go
When resetting workflows in batch, start also looking for `WORKFLOW_TASK_FAILED_CAUSE_NON_DETERMINISTIC_ERROR` causes to identify failures of non-deterministic type
resolve #186
1. Closes 
=> Address tasks not recognized as failed with non-determenistic cause

cli/workflowCommands.go
- Adds workflow status
- Removes ExecutionTime from the `--fields long` output to fit ~1920* px screen
```
./tctl w l                                                                                                                    INT ✘ 
Status          WorkflowId                  Name               StartTime     
Running     f0f0aa_Running          RainbowStatusesWorkflow    11 minutes ago  
TimedOut    f0f0aa_TimedOut         RainbowStatusesWorkflow    11 minutes ago  
Completed   f0f0aa_ContinuedAsNew   RainbowStatusesWorkflow    11 minutes ago  
Terminated  f0f0aa_Terminated       RainbowStatusesWorkflow    11 minutes ago  
Failed      f0f0aa_Failed           RainbowStatusesWorkflow    11 minutes ago  
Canceled    f0f0aa_Canceled         RainbowStatusesWorkflow    11 minutes ago …
```
=> Print Workflow Type and Status when printing workflows

cli/app.go, go.mod, go.sum
Enables suggestions for commands and flags (was recently introduced to urfave/cli/v2)
UX
urfave/cli/v2 PR https://github.com/urfave/cli/pull/1390
1. Closes 
```
tctl workflow list -archive
Incorrect Usage: flag provided but not defined: -archive
Did you mean '--archived'?
```
=> Enable suggestions for commands and flags

cli/workflow_commands.go
Starts printing Execution Time with `tctl workflow describe`
resolve #105
1. Closes 
```
./tctl w d -wid f0f0aa_Running
{
"executionConfig": {
"taskQueue": {
"name": "rainbow-statuses"
...
"workflowExecutionInfo": {
"execution": {
"workflowId": "f0f0aa_Running",
"runId": "afc19ece-40eb-49ac-babe-b632e36093e5"
},
"executionTime": "2022-05-18T17:06:16.438730163Z",
...
}
```
=> Print execution time when describing workflow

cli/flags.go
- Updated the `--help` output for flags that accept multiple inputs and removed explicit messaging on how to pass multiple. 
- urfave/cli already prints `(accepts multiple inputs)` for slice flags by default, no need to manually add that
- updated the help output text based on https://docs.temporal.io/docs/tctl/workflow/run
1. Closes 
=> Update --help output for slice flags

cli/app_test.go, cli/defs.go, cli/workflow_commands.go
This fixes the ability to start workflows without search attributes in the 0.17 beta.
A bug in the parsing code would pass a bogus search attribute to the server when none were specified on the command line:
```
client.StartWorkflowOptions { SearchAttributes: { "[]": "" } }
```
There are some new tests, as well as new assertions in old tests which failed before changing the parsing logic.
Nope!
=> Fix search attribute parsing when starting workflows in .17 beta

cli/app.go, cli/headers/headers.go
Bump versions to `1.16.2` and `1.17.0-alpha.2`.
To support new server release.
=> Bump versions to 1.16.2 and 1.17.0-alpha.2

cli/flags.go, cli/util.go, cli/util_test.go, cli/workflow.go, cli/workflow_commands.go
This adds the base for the workflow `trace` command (called `texp` at Datadog) discussed in the Slack channel. 
Rather than adding all the changes at once, I'd rather add the changes in small chunks so they're easier to digest and there's a proper feedback loop.
1. Opens the texp upstream (should I create a ticket?)
- Manually (run `tctl w trace --help`, `tctl w trace --wid a --rid b`)
Not yet
=> Add workflow trace command

cli/trace/execution_state.go, cli/trace/execution_state_test.go
This PR adds the `ExecutionState` interface which is necessary to implement the trace. The ExecutionState provides a common interface to any execution (Workflows, Activities and Timers in this case) updated through HistoryEvents. We will use this to keep updated information about workflow executions and their childs so we can represent it in the terminal.
Due to this more extended concept of executions (maybe we should use another name for this?) not being in the Temporal SDK, we have implemented Status for both Activities and Timers so we can know the state of those.
Child Workflows can be updated through the parent (using `EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_*` events) or by updating the workflow itself. This will be implemented in another PR where the `GetHistoryEvents` and the …
=> Add execution states necessary for trace

cli/app.go, cli/app_test.go, cli/commands.go, cli/config.go, cli/flags.go, cli/namespace.go, cli/namespace_commands.go, cli/namespace_utils.go, cli/util.go, cli/workflow.go
--namespace flag now lives under each subcommand instead of as a global flag
- Namaspace relates to specific Temporal actions rather than global property (TLS, auth) 
- changes the syntax from `tctl  --namespace canary namespace register` to `tctl namespace register --namespace canary`
1. Closes 
- unit tests
- registered and deleted namespace
=> Move namespace flag from global to every command

cli_curr/admin.go, cli_curr/adminCommands.go
- Call service api for admin workflow delete command
- For 1.17.3 release. Server doesn't have tdbg in 1.17 release. But customer may this admin workflow to delete some corrupted workflows
1. Closes 
=> Call service api for admin workflow delete command

cli/config.go, cli/schedule_commands.go, cli/util.go, cli_curr/config.go, cmd/tctl/main.go, go.mod, go.sum
changes config feature semantics from flags to args
`tctl config set --namespace accounting` 
to 
`tctl config set env.local.namespace accounting`  (or `tctl config set namespace accounting` for short in a new PR)
- moving towards allowing to configure the default value for any flag and not just the ones whitelisted by `tctl config set` command   
- consistency with other tools such as `git` and `kubectl` 
1. Closes 
=> Change config semantics to args and full key path

cli/app.go, cli/config.go, cli/factory.go, cli/util.go
Populates unset command flags with values from the config feature 
Allows to set/read any flag through config
1. Closes 
=> Populate all command flags from config

cli/app.go, cli/app_test.go, cli/commands.go, cli/namespace_commands.go, cli/util.go
This reverts commit 614a43de7ee4816bae3241d3e9813424cb6902f4.
reverted `--namespace` flag back to global
as per API discussion review
1. Closes 
=> Revert "Move namespace flag from global to every command (#236)"

cli/app_test.go, cli/cluster.go, cli/commands.go, cli/namespace.go, cli/schedule.go, cli/task_queue.go, cli/workflow.go
Removed all aliases for commands such as `tctl w l` for `tctl workflow list`
decision from an API review @bergundy @alexshtin 
users still can set their own aliases using `tctl alias`
1. Closes 
unit tests
=> Remove aliases for commands

cli/workflow.go, cli/workflow_commands.go
Remove `workflow scan` command.
`ScanWorkflow` API is about to be deprecated from server and should not be exposed in new `tctl`.
=> Remove workflow scan command

cli/app_test.go, cli/config.go, cli/env.go, cli/namespace.go, cli/namespace_commands.go
Use args for namespace name instead of global flag for `namespace` command.
`namespace delete` can't use global flag because in this case it will delete `default` namespace if simple 
```
$ tctl namespace delete
```
is executed.
I changed all other namespace commands for consistency.
=> Use args for namespace name instead of global flag

cli/batch.go, cli/batch_commands.go, cli/batch_test.go
- Renamed `tctl batch terminate` to `stop` in accordance with API
- `tctl batch stop` now uses official API
- `tctl batch describe` now uses official API
stabilizing by using the official API
1. Closes 
manual run + new unit test
=> Refactor batch stop and describe commands to use API

cli/app.go
Removed the prompt asking whether to continue w/o config loaded
the prompt would result in a stuck experience in cicds (where config feature also unlikely to be used, and if it is, the values will fallback to default namespace and default values)
1. Closes 
=> Do not prompt on config error

cli/batch.go, cli/batch_commands.go, cli/batch_test.go
Changed:
* `batch start --batch-type terminate` -> `batch terminate`
* `batch start --batch-type cancel` -> `batch cancel`
* `batch start --batch-type signal` -> `batch signal`
easier to type / discover
1. Closes 
Updated unit tests
=> Transform batch start into concrete terminate/.. commands

cli/namespace.go, cli/namespace_commands.go, cli/namespace_test.go, cli/namespace_utils.go
- Changed namespace `--data` key-value separator from `:` to `=`
- Transformed namespace `--data` into a slice:
Example:
before
`tctl namespace register --data k1:v1,k2:v2` 
after
`tctl namespace register --data k1=v1 --data k2=v2`
Consistency with other multi-value flags  such as `--input`, `--search-attribute`
1. Closes 
added unit test + manual run `tctl namespace register --data k1=v1 --data k2=v2 test1`
=> Transform Namespace --data into a slice

cli/flags.go, cli/namespace_commands.go, cli/namespace_test.go, cli/namespace_utils.go
- Changed namespace `--cluster plus cluster args` into a slice
previous syntax for clusters was pretty ugly. It was requiring to set --cluster to specify just one cluster name, then the `args[1:]` would mean the rest of the cluster (after namespace arg)
before
```
tctl namespace register --cluster active my-namespace standby
```
after
```
tctl namespace register --cluster active --cluster standby my-namespace  
```
1. Closes 
added unit test
=> Transform Namespace --cluster + args into a slice

cli/namespace_commands.go, cli/util.go, cli/util_test.go
Allowed values in `key=value` to contain an equal `=` sign
```
tctl namespace register --data k1=value=with=equal
```
1. Closes 
added unit test
=> Allow key=value flags to have equal in value

cli/flags.go, cli/namespace_commands.go, cli/schedule.go, cli/util.go, cli/util_test.go, cli/workflow_commands.go, cli/workflow_test.go
- Search Attributes and Memo are now expected to be passed as `key=value` instead of separate key and value flags
- Made memo accept both --memo and --memo-file at a time
typing experience
1. Closes 
unit tests
=> Make search attributes and memo follow key=value format

cli/env.go
It was missing a newline, which resulted in merging stdout with shell prompt:
```
tctl config current-env                                                                                                                                                                             
ruslan% 
```
ux
1. Closes 
=> Add new line when printing current env

cli/app.go, cli/data_converter_commands.go, cli/factory.go, cli/headersprovider/headers_provider.go, cli/util.go, cli/workflow_commands.go, cli_curr/app.go, cli_curr/factory.go, cli_curr/util.go, cli_curr/workflowCommands.go, cmd/plugins/tctl-authorization-plugin/main.go, cmd/tctl/main.go, go.mod
Set the mod version to v1
As we are not currently releasing v2 the mod version conflicts with the github release version, resulting in not being able to import the module in other projects
1. Closes 
unit tests
=> Set module version to v1

README.md
Config key for version is just `version`, sans --
Tested by copying command from readme, getting a CLI parse error, then removing the `--` to  get expected behavior.
=> fix syntax on `tctl config set` in readme

cli/plugin.go, cli/use_dynamic_commands.go
change syscall.Exec for command.Run to avoid a complete replacement of the current Go process with another for external plugin execution.
Fixes https://github.com/temporalio/tctl/issues/321
If I register a headers provider plugin, this plugin will be spawn and started. Then I execute an external plugin, the current code will replace the current Go process with another by calling syscall.Exec. The side effect is that the app.After will never be called and the header provide plugin will stay and will not be stopped
1. Closes  
https://github.com/temporalio/tctl/issues/321
2. How was this tested
export TEMPORAL_CLI_PLUGIN_HEADERS_PROVIDER=tctl-authorization
tctl yo
check that tctl-authorization is not running anymore
3. Any docs updates needed
=> change syscall.Exec for command.Run to avoid a complete replacement of the current Go process with another

cli/use_dynamic_commands.go
After asuccesful external plugin execution the current code will print that the command is not found.
Add a simple return to avoid this print
=> Avoid printing that the plugin is not found when it was

cli_curr/app.go
Added a deprecation notion to `tctl batch`
there is a new `tctl batch-v2` entry for batch commands
1. Closes 
unit tests
=> Deprecate batch command in favor of API version

.vscode/launch.json, cli_curr/adminCommands.go
`tctl admin wf show  --namespace_id c61bddba-0450-4a4b-827f-fdd8578a9fd1 -w hello_world_workflowID -r a8b819e4-c9a3-4137-ba6a-e9fbd976d851` 
returns error "Error: Global option namespace_id is required" while `namespace_id` is not a global option.
With the fix, `tctl admin wf show` works again.
1. Closes 
Manual test
=> Fix --namespace_id option for tctl admin workflow command

cli_curr/app_test.go, cli_curr/workflow.go
Make `--input` for `workflow signal` accept multiple inputs
closes https://github.com/temporalio/tctl/issues/344
supporting passing multiple input JSONs
1. Closes 
verified multiple inputs are included in Payloads
=> Accept multiple inputs for signal

cli_curr/adminCommands.go
`tctl admin wf refresh_tasks --namespace_id tao.a2dd6 -w hello_world_workflowID-817677000`
returns error "Error: Global option namespace_id is required" while namespace_id is not a global option.
With the fix, tctl admin wf show works again.
Similar regression for another command: https://github.com/temporalio/tctl/pull/345
1. Closes 
Manual
=> Fix namespace_id flag for AdminRefreshWorkflowTasks

README.md
Visibly deprecates `tctl`. Adds caution note to README and redirect to docs for Temporal CLI.
After, repository needs to be archived.
=> SDK-319: Updates `tctl` README for deprecation notice

.github/workflows/trigger-publish.yml
Fix token to trigger publish workflow.
This workflow has been failing for months...
1. Closes 
=> [GHA] Fix token to trigger publish workflow
